spring:
  application:
    name: SoftArchDesigner
  autoconfigure:
    exclude:
      - com.alibaba.cloud.ai.autoconfigure.dashscope.DashScopeAgentAutoConfiguration
      - com.alibaba.cloud.ai.autoconfigure.dashscope.DashScopeChatAutoConfiguration
      - org.springframework.ai.model.openai.autoconfigure.OpenAiChatAutoConfiguration
  ai:
    openai:
      api-key: sk_DK3AMAdV0XbcwdQNff4PCHTYdZKRIZ8qCMgl0qifZHo
      base-url: https://api.ppio.com/openai
      chat:
        options:
          model: pa/gpt-5.4
          temperature: 1

server:
  port: 8082

softarch:
  logs-dir: logs
  output-dir: output
